### PR TITLE
Remove Coveralls

### PR DESCRIPTION
**Pull request by penibelst**
Coveralls is a plague. Code Climate can check the coverage too. Should I add the coverage from Code Climate?

### CODE REVIEW

**Comment by stefanozanella** [comment]
I must admit that I didn't look into the evolution of both tools for quite some time. Why do you say Coveralls is bad? (I ask so that I'll have an argument if anybody asks me in the future ;)

As per the PR, if you merge master and change its scope to something like "replace coveralls with code climate", it's good to go for me!

**Comment by penibelst** [comment]
Coveralls is not maintained.

All you need to add, is the Code Climate token in the travis config http://docs.travis-ci.com/user/code-climate/

**Comment by stefanozanella** [comment]
I made a PR starting from yours with the repo token. Thanks again for the effort!

**Comment by penibelst** [comment]
Very nice.

**Pull request closed without merging**
